-- Patch 32: Add reply_to_log_id to exercise_logs for AI reply cards.
-- AI cards generated by per-log events (heist, spam surge, etc.) will reference
-- the specific log that triggered them so the Flutter feed can render them as replies.

ALTER TABLE public.exercise_logs
  ADD COLUMN IF NOT EXISTS reply_to_log_id uuid
    REFERENCES public.exercise_logs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_exercise_logs_reply_to
  ON public.exercise_logs(reply_to_log_id)
  WHERE reply_to_log_id IS NOT NULL;
