/**
 * Reads lib/core/exercise_data.dart and prints SQL to sync public.exercises
 * system rows (created_by = 'system') with kSystemExercises:
 *   1) UPDATE all matching rows by exact name
 *   2) INSERT missing (name, room) pairs for every room
 *
 * Run: node tool/generate_system_exercises_sync_sql.mjs > supabase_patches/NN_sync_system_exercises.sql
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const srcPath = path.join(root, "lib", "core", "exercise_data.dart");
const src = fs.readFileSync(srcPath, "utf8");

const startMarker = "const kSystemExercises = <ExerciseDefinition>[";
const start = src.indexOf(startMarker);
if (start < 0) throw new Error("kSystemExercises not found");
const slice = src.slice(start + startMarker.length);
const end = slice.indexOf("];");
if (end < 0) throw new Error("end of kSystemExercises not found");
const body = slice.slice(0, end);

const blocks = body.split(/ExerciseDefinition\s*\(/).slice(1);

function unescapeDartString(s) {
  return s.replace(/\\'/g, "'").replace(/\\\\/g, "\\");
}

function parseBlock(block) {
  const id = /id:\s*'((?:\\'|[^'])*)'/.exec(block);
  const name = /name:\s*'((?:\\'|[^'])*)'/.exec(block);
  const points = /points:\s*([0-9.]+)/.exec(block);
  const icon = /icon:\s*'((?:\\'|[^'])*)'/.exec(block);
  const category = /category:\s*'((?:\\'|[^'])*)'/.exec(block);
  const sw = /supportsWeight:\s*(true|false)/.exec(block);
  const wt = /weightThreshold:\s*([0-9.]+)/.exec(block);
  const wm = /weightMultiplier:\s*([0-9.]+)/.exec(block);
  const cu = /countUnit:\s*CountUnit\.(\w+)/.exec(block);
  const tpm = /timePointsMode:\s*TimePointsMode\.(\w+)/.exec(block);
  const timer = /timerUiPreferred:\s*(true|false)/.exec(block);

  if (!id || !name || !points || !icon || !category) {
    throw new Error(`Incomplete ExerciseDefinition near id=${id?.[1] ?? "?"}`);
  }

  let countUnit = cu ? cu[1].toLowerCase() : "reps";
  if (countUnit === "reps") countUnit = "reps";
  else if (countUnit === "seconds") countUnit = "seconds";
  else if (countUnit === "minutes") countUnit = "minutes";
  else throw new Error(`Unknown CountUnit: ${cu[1]}`);

  let timePointsMode = "null";
  if (tpm) {
    const m = tpm[1];
    if (m === "perSecond") timePointsMode = "'per_second'";
    else if (m === "perMinute") timePointsMode = "'per_minute'";
    else throw new Error(`Unknown TimePointsMode: ${m}`);
  }

  const usesTime = countUnit === "seconds" || countUnit === "minutes";
  const timerUi = timer ? timer[1] === "true" : false;

  return {
    id: unescapeDartString(id[1]),
    name: unescapeDartString(name[1]),
    points: parseFloat(points[1]),
    icon: unescapeDartString(icon[1]),
    category: unescapeDartString(category[1]),
    supportsWeight: sw ? sw[1] === "true" : false,
    weightThreshold: wt ? parseFloat(wt[1]) : null,
    weightMultiplier: wm ? parseFloat(wm[1]) : null,
    countUnit,
    timePointsMode,
    usesTime,
    timerUi: timer ? timer[1] === "true" : timerUi,
  };
}

const exercises = blocks.map((b, i) => {
  try {
    return parseBlock(b);
  } catch (e) {
    throw new Error(`${e.message} (block index ${i})`);
  }
});

function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

function rowSql(e) {
  const wt =
    e.weightThreshold != null ? String(e.weightThreshold) : "null::double precision";
  const wm =
    e.weightMultiplier != null ? String(e.weightMultiplier) : "null::double precision";
  const tpm =
    e.timePointsMode === "null" ? "null::text" : e.timePointsMode;
  return `(
  ${sqlStr(e.name)},
  ${e.points}::double precision,
  ${sqlStr(e.icon)},
  ${sqlStr(e.category)},
  ${e.supportsWeight}::boolean,
  ${wt},
  ${wm},
  ${sqlStr(e.countUnit)},
  ${tpm},
  ${e.usesTime}::boolean,
  ${e.timerUi}::boolean
)`;
}

const valuesList = exercises.map(rowSql).join(",\n");

console.log(`-- Generated by tool/generate_system_exercises_sync_sql.mjs — do not edit by hand.
-- Syncs system exercises (created_by = 'system') to match lib/core/exercise_data.dart.
--
-- Matching: rows are updated by exact exercise [name] as stored in the DB.
-- If you renamed an exercise in Dart, old-name rows are not updated; run a manual
-- UPDATE or delete orphans. New exercises are inserted for every room that lacks them.
--
BEGIN;

-- 1) Update existing system rows where the name matches the catalog.
UPDATE public.exercises AS e
SET
  name = v.name,
  points = v.points,
  icon = v.icon,
  category = v.category,
  supports_weight = v.supports_weight,
  weight_threshold = v.weight_threshold,
  weight_multiplier = v.weight_multiplier,
  count_unit = v.count_unit,
  time_points_mode = v.time_points_mode,
  uses_time = v.uses_time,
  timer_ui = v.timer_ui
FROM (
  VALUES
${valuesList}
) AS v(
  name,
  points,
  icon,
  category,
  supports_weight,
  weight_threshold,
  weight_multiplier,
  count_unit,
  time_points_mode,
  uses_time,
  timer_ui
)
WHERE e.created_by = 'system'
  AND e.name = v.name;

-- 2) Insert catalog exercises missing from each room (new exercises / old rooms).
INSERT INTO public.exercises (
  room_id,
  name,
  points,
  icon,
  category,
  supports_weight,
  weight_threshold,
  weight_multiplier,
  created_by,
  count_unit,
  time_points_mode,
  uses_time,
  timer_ui
)
SELECT
  r.id,
  v.name,
  v.points,
  v.icon,
  v.category,
  v.supports_weight,
  v.weight_threshold,
  v.weight_multiplier,
  'system',
  v.count_unit,
  v.time_points_mode,
  v.uses_time,
  v.timer_ui
FROM public.rooms AS r
CROSS JOIN (
  VALUES
${valuesList}
) AS v(
  name,
  points,
  icon,
  category,
  supports_weight,
  weight_threshold,
  weight_multiplier,
  count_unit,
  time_points_mode,
  uses_time,
  timer_ui
)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.exercises AS e
  WHERE e.room_id = r.id
    AND e.created_by = 'system'
    AND e.name = v.name
);

COMMIT;
`);
