import 'count_unit.dart';

class ExerciseDefinition {
  final String id;
  final String name;
  final double points;
  final String icon;
  final String category;
  final bool supportsWeight;
  final double? weightThreshold;
  final double? weightMultiplier;

  /// `reps` | `seconds` | `minutes` — must match DB `count_unit`.
  final CountUnit countUnit;

  /// Only when [countUnit] is [CountUnit.seconds]: `per_second` (plank) vs `per_minute` (sports blocks).
  final TimePointsMode? timePointsMode;

  /// Stopwatch tap UI (plank / holds). Stored as `timer_ui` in Postgres.
  final bool timerUiPreferred;

  const ExerciseDefinition({
    required this.id,
    required this.name,
    required this.points,
    required this.icon,
    required this.category,
    this.supportsWeight = false,
    this.weightThreshold,
    this.weightMultiplier,
    this.countUnit = CountUnit.reps,
    this.timePointsMode,
    this.timerUiPreferred = false,
  });

  /// Persisted as `uses_time` — true when logging time, not rep count.
  bool get usesTime => countUnit != CountUnit.reps;
}

const kSystemExercises = <ExerciseDefinition>[
  // Upper Body
  ExerciseDefinition(
    id: 'pushups',
    name: 'Push-ups',
    points: 2,
    icon: '💪',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'explosive_pushups',
    name: 'Explosive Push-ups',
    points: 3,
    icon: '⚡',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'diamond_pushups',
    name: 'Diamond Push-ups',
    points: 3.6,
    icon: '💎',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'pullups',
    name: 'Pull-ups',
    points: 4.5,
    icon: '🏋️',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 1.25,
  ),
  ExerciseDefinition(
    id: 'wide_grip_pullups',
    name: 'Wide Grip Pull-ups',
    points: 5,
    icon: '📏',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 1.25,
  ),
  ExerciseDefinition(
    id: 'one_arm_pullups',
    name: 'One-Arm Pull-ups',
    points: 10,
    icon: '💪💪',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 1.5,
  ),
  ExerciseDefinition(
    id: 'dips',
    name: 'Dips',
    points: 3.8,
    icon: '🔽',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1.1,
  ),
  ExerciseDefinition(
    id: 'chair_dips',
    name: 'Chair Dips',
    points: 1.5,
    icon: '🪑',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'handstand_pushups',
    name: 'Handstand Push-ups',
    points: 6,
    icon: '🤸',
    category: 'Upper Body',
  ),
  ExerciseDefinition(
    id: 'incline_pushups',
    name: 'Incline Push-ups',
    points: 1.5,
    icon: '⬆️',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'clap_pushups',
    name: 'Clap Push-ups',
    points: 3.5,
    icon: '👏',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'decline_pushups',
    name: 'Decline Push-ups',
    points: 3.2,
    icon: '🔻',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'archer_pushups',
    name: 'Archer Pushups',
    points: 4,
    icon: '🏹',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1.1,
  ),
  ExerciseDefinition(
    id: 'chin_ups',
    name: 'Chin Ups',
    points: 4.25,
    icon: '🏋️‍♂️',
    category: 'Upper Body',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 1.2,
  ),

  // Core
  ExerciseDefinition(
    id: 'situps',
    name: 'Sit-ups',
    points: 1.2,
    icon: '🔄',
    category: 'Core',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'plank',
    name: 'Plank',
    points: 1,
    icon: '⚰️',
    category: 'Core',
    countUnit: CountUnit.seconds,
    timePointsMode: TimePointsMode.perSecond,
    timerUiPreferred: true,
  ),
  ExerciseDefinition(
    id: 'crunches',
    name: 'Crunches',
    points: 1,
    icon: '🌟',
    category: 'Core',
  ),
  ExerciseDefinition(
    id: 'lsit_hold',
    name: 'L-Sit Hold',
    points: 2.5,
    icon: '📏',
    category: 'Core',
    countUnit: CountUnit.seconds,
    timePointsMode: TimePointsMode.perSecond,
    timerUiPreferred: true,
  ),
  ExerciseDefinition(
    id: 'abwheel_knees',
    name: 'Ab Wheel (Knees)',
    points: 2.5,
    icon: '⚙️',
    category: 'Core',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'abwheel_full',
    name: 'Ab Wheel (Full)',
    points: 4,
    icon: '⚙️',
    category: 'Core',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 1.1,
  ),
  ExerciseDefinition(
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    points: 1.4,
    icon: '🚴',
    category: 'Core',
  ),
  ExerciseDefinition(
    id: 'russian_twist',
    name: 'Russian Twist',
    points: 1,
    icon: '🔄',
    category: 'Core',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'leg_raises',
    name: 'Leg Raises',
    points: 2,
    icon: '🍗',
    category: 'Core',
  ),

  // Lower Body
  ExerciseDefinition(
    id: 'squats',
    name: 'Squats',
    points: 1,
    icon: '🦵',
    category: 'Lower Body',
    supportsWeight: true,
    weightThreshold: 15,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'jump_squats',
    name: 'Jump Squats',
    points: 3,
    icon: '⬆️',
    category: 'Lower Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'bulgarian_split_squats',
    name: 'Bulgarian Split Squats',
    points: 2.5,
    icon: '🇧🇬',
    category: 'Lower Body',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1,
  ),
  ExerciseDefinition(
    id: 'lunges',
    name: 'Lunges',
    points: 1,
    icon: '🚶',
    category: 'Lower Body',
    supportsWeight: true,
    weightThreshold: 12.5,
    weightMultiplier: 0.9,
  ),
  ExerciseDefinition(
    id: 'glute_bridges',
    name: 'Glute Bridges',
    points: 1.4,
    icon: '🌉',
    category: 'Lower Body',
  ),
  ExerciseDefinition(
    id: 'pistol_squats',
    name: 'Pistol Squats',
    points: 4.5,
    icon: '🔫',
    category: 'Lower Body',
    supportsWeight: true,
    weightThreshold: 7.5,
    weightMultiplier: 1.25,
  ),

  // Full Body
  ExerciseDefinition(
    id: 'burpees',
    name: 'Burpees',
    points: 4,
    icon: '⚡',
    category: 'Full Body',
  ),
  ExerciseDefinition(
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    points: 1,
    icon: '⛰️',
    category: 'Full Body',
  ),

  // Cardio
  ExerciseDefinition(
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    points: 0.5,
    icon: '🦘',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'high_knees',
    name: 'High Knees',
    points: 0.5,
    icon: '🏃',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'skaters',
    name: 'Skaters',
    points: 0.5,
    icon: '⛸️',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'jump_rope',
    name: 'Jump Rope',
    points: 0.5,
    icon: '🤾',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'box_jumps',
    name: 'Box Jumps',
    points: 3,
    icon: '📦',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'running1',
    name: 'Running',
    points: 2.5,
    icon: '🏃🏿',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'running2',
    name: 'Running(1 mile)',
    points: 40,
    icon: '🏃‍♂️',
    category: 'Cardio',
  ),
  ExerciseDefinition(
    id: 'soccer',
    name: 'Futbol/Soccer',
    points: 3,
    icon: '⚽',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'basketball',
    name: 'Basketball',
    points: 3,
    icon: '🏀',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'swimming',
    name: 'Swimming',
    points: 3.5,
    icon: '🏊',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'cycling',
    name: 'Cycling',
    points: 2.5,
    icon: '🚴',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'tennis',
    name: 'Tennis',
    points: 2,
    icon: '🎾',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'golf',
    name: 'Golf',
    points: 0.75,
    icon: '⛳',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'volleyball',
    name: 'Volleyball',
    points: 2,
    icon: '🏐',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'baseball',
    name: 'Baseball',
    points: 1.5,
    icon: '⚾',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),
  ExerciseDefinition(
    id: 'football',
    name: 'American Football',
    points: 3.5,
    icon: '🏈',
    category: 'Cardio',
    countUnit: CountUnit.minutes,
  ),

  // Strength
  ExerciseDefinition(
    id: 'bicep_curls',
    name: 'Bicep Curls',
    points: 2.5,
    icon: '💪',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'overhead_press',
    name: 'Overhead Press',
    points: 3.5,
    icon: '🏋️‍♂️',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1.1,
  ),
  ExerciseDefinition(
    id: 'tricep_extensions',
    name: 'Tricep Extensions',
    points: 3,
    icon: '💪',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 5,
    weightMultiplier: 0.75,
  ),
  ExerciseDefinition(
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    points: 4,
    icon: '🏋️',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 10,
    weightMultiplier: 1.1,
  ),
  ExerciseDefinition(
    id: 'bench_press',
    name: 'Bench Press',
    points: 5,
    icon: '🏋️‍♂️',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 15,
    weightMultiplier: 1.25,
  ),
  ExerciseDefinition(
    id: 'deadlift',
    name: 'Deadlift',
    points: 6,
    icon: '🏋️‍♂️',
    category: 'Strength',
    supportsWeight: true,
    weightThreshold: 20,
    weightMultiplier: 1.5,
  ),
  ExerciseDefinition(
  id: 'pike_pushups',
  name: 'Pike Push-ups',
  points: 3.8,
  icon: '🔺',
  category: 'Upper Body',
  supportsWeight: true,
  weightThreshold: 10,
  weightMultiplier: 1,
),

ExerciseDefinition(
  id: 'negative_pullups',
  name: 'Negative Pull-ups',
  points: 3.2,
  icon: '⬇️',
  category: 'Upper Body',
),

ExerciseDefinition(
  id: 'australian_pullups',
  name: 'Australian Pull-ups',
  points: 2.8,
  icon: '📏',
  category: 'Upper Body',
),

ExerciseDefinition(
  id: 'ring_dips',
  name: 'Ring Dips',
  points: 4.8,
  icon: '⭕',
  category: 'Upper Body',
  supportsWeight: true,
  weightThreshold: 7.5,
  weightMultiplier: 1.2,
),

ExerciseDefinition(
  id: 'handstand_hold',
  name: 'Handstand Hold',
  points: 1.2,
  icon: '🤸',
  category: 'Upper Body',
  countUnit: CountUnit.seconds,
  timePointsMode: TimePointsMode.perSecond,
  timerUiPreferred: true,
),
ExerciseDefinition(
  id: 'calf_raises',
  name: 'Calf Raises',
  points: 0.9,
  icon: '🦶',
  category: 'Lower Body',
  supportsWeight: true,
  weightThreshold: 10,
  weightMultiplier: 0.8,
),

ExerciseDefinition(
  id: 'step_ups',
  name: 'Step-ups',
  points: 1.8,
  icon: '🪜',
  category: 'Lower Body',
  supportsWeight: true,
  weightThreshold: 10,
  weightMultiplier: 1,
),

ExerciseDefinition(
  id: 'nordic_curls',
  name: 'Nordic Curls',
  points: 4.8,
  icon: '🧎',
  category: 'Lower Body',
),

ExerciseDefinition(
  id: 'wall_sit',
  name: 'Wall Sit',
  points: 1.3,
  icon: '🧱',
  category: 'Lower Body',
  countUnit: CountUnit.seconds,
  timePointsMode: TimePointsMode.perSecond,
  timerUiPreferred: true,
),ExerciseDefinition(
  id: 'thrusters',
  name: 'Thrusters',
  points: 4.5,
  icon: '🏋️',
  category: 'Full Body',
  supportsWeight: true,
  weightThreshold: 10,
  weightMultiplier: 1.2,
),

ExerciseDefinition(
  id: 'clean_press',
  name: 'Clean & Press',
  points: 5.5,
  icon: '💥',
  category: 'Full Body',
  supportsWeight: true,
  weightThreshold: 12.5,
  weightMultiplier: 1.3,
),

ExerciseDefinition(
  id: 'kettlebell_swings',
  name: 'Kettlebell Swings',
  points: 3,
  icon: '🔔',
  category: 'Full Body',
  supportsWeight: true,
  weightThreshold: 10,
  weightMultiplier: 1,
),ExerciseDefinition(
  id: 'sprinting',
  name: 'Sprinting',
  points: 4,
  icon: '💨',
  category: 'Cardio',
  countUnit: CountUnit.minutes,
),

ExerciseDefinition(
  id: 'rowing',
  name: 'Rowing',
  points: 3.2,
  icon: '🚣',
  category: 'Cardio',
  countUnit: CountUnit.minutes,
),

ExerciseDefinition(
  id: 'stair_climbing',
  name: 'Stair Climbing',
  points: 2.5,
  icon: '🪜',
  category: 'Cardio',
  countUnit: CountUnit.minutes,
),

ExerciseDefinition(
  id: 'hiking',
  name: 'Hiking',
  points: 2.2,
  icon: '🥾',
  category: 'Cardio',
  countUnit: CountUnit.minutes,
),ExerciseDefinition(
  id: 'muscle_ups',
  name: 'Muscle-ups',
  points: 9,
  icon: '🚀',
  category: 'Upper Body',
),

ExerciseDefinition(
  id: 'planche_hold',
  name: 'Planche Hold',
  points: 6,
  icon: '🛸',
  category: 'Upper Body',
  countUnit: CountUnit.seconds,
  timePointsMode: TimePointsMode.perSecond,
  timerUiPreferred: true,
),

ExerciseDefinition(
  id: 'front_lever_hold',
  name: 'Front Lever Hold',
  points: 5,
  icon: '📏',
  category: 'Upper Body',
  countUnit: CountUnit.seconds,
  timePointsMode: TimePointsMode.perSecond,
  timerUiPreferred: true,
)
];

const kExerciseCategories = [
  'Upper Body',
  'Core',
  'Lower Body',
  'Full Body',
  'Cardio',
  'Strength',
  'Custom',
];